[MeterBar0]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
[MeterBar1]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
[MeterBar2]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
[MeterBar3]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
[MeterBar4]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
[MeterBar5]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
[MeterBar6]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
[MeterBar7]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
[MeterBar8]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
[MeterBar9]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
[MeterBar10]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
[MeterBar11]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]