[MeterShadowBar0]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
[MeterShadowBar1]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
[MeterShadowBar2]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
[MeterShadowBar3]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
[MeterShadowBar4]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
[MeterShadowBar5]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
[MeterShadowBar6]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
[MeterShadowBar7]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
[MeterShadowBar8]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
[MeterShadowBar9]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
[MeterShadowBar10]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
[MeterShadowBar11]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]